org: shivam087r
app: aws-node-http-api-project
service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:318499227335:table/InsertToDo

functions:
  hello:
    handler: src/hello.handler
    events:
      - httpApi:
          path: /
          method: get
  InsertToDo:
    handler: src/InsertToDo.handler
    events:
      - httpApi:
          path: /kaam
          method: post
  Showtodo:
    handler: src/ShowToDo.handler
    events:
      - httpApi:
          path: /kaam
          method: get
  FinishToDo:
    handler: src/FinishToDo.handler
    events:
      - httpApi:
          path: /kaam/{id}
          method: put

resources:
  Resources:
    InsertToDo:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: InsertToDo
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
